<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Room Asset List</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; font-size: 12px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #444; padding-bottom: 10px; }
        .logo { height: 60px; margin-bottom: 10px; }
        .title { font-size: 18px; font-weight: bold; text-transform: uppercase; }
        .info-grid { width: 100%; margin-bottom: 20px; }
        .info-grid td { padding: 5px; border: 1px solid #eee; }
        .label { font-weight: bold; background-color: #f9f9f9; width: 120px; }
        
        table.assets { width: 100%; border-collapse: collapse; margin-top: 20px; }
        table.assets th { background-color: #efefef; border: 1px solid #ccc; padding: 8px; text-align: left; font-size: 11px; }
        table.assets td { border: 1px solid #ccc; padding: 8px; font-size: 11px; }
        
        .footer { margin-top: 50px; width: 100%; }
        .signature-box { width: 45%; display: inline-block; vertical-align: top; }
        .sig-line { border-top: 1px solid #000; margin-top: 60px; padding-top: 5px; text-align: center; }
        .sig-name { font-weight: bold; font-size: 13px; }
        .sig-title { font-style: italic; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        @php
            $logo = \App\Models\Setting::get('company_logo');
            $companyName = \App\Models\Setting::get('company_name', 'NSDO Procurement');
        @endphp
        
        @if($logo && file_exists(storage_path('app/public/' . $logo)))
            <img src="data:image/png;base64,{{ base64_encode(file_get_contents(storage_path('app/public/' . $logo))) }}" class="logo">
        @endif
        <div class="title">{{ $companyName }}</div>
        <div style="font-size: 14px; margin-top: 5px;">Room Inventory Asset List</div>
    </div>

    <table class="info-grid">
        <tr>
            <td class="label">Room / Office:</td>
            <td>{{ $room }}</td>
            <td class="label">Date:</td>
            <td>{{ $date }}</td>
        </tr>
        <tr>
            <td class="label">Province:</td>
            <td>{{ $province }}</td>
            <td class="label">Department:</td>
            <td>{{ $department }}</td>
        </tr>
    </table>

    <table class="assets">
        <thead>
            <tr>
                <th width="15%">Asset Tag</th>
                <th width="30%">Asset Name / Description</th>
                <th width="15%">Type</th>
                <th width="20%">Handedover to</th>
                <th width="10%">Qty</th>
                <th width="10%">Condition</th>
            </tr>
        </thead>
        <tbody>
            @foreach($assets as $asset)
                <tr>
                    <td style="font-weight: bold;">{{ $asset->asset_tag }}</td>
                    <td>
                        {{ $asset->name }}
                        @if($asset->description)
                            <div style="font-size: 9px; color: #666;">{{ $asset->description }}</div>
                        @endif
                    </td>
                    <td>{{ $asset->assetType->name ?? 'N/A' }}</td>
                    <td>{{ $asset->staff->name ?? 'N/A' }}</td>
                    <td align="center">{{ $asset->quantity }}</td>
                    <td>{{ $asset->condition }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <div class="signature-box" style="float: left;">
            <p><strong>Prepared By:</strong></p>
            <div class="sig-line">
                <div class="sig-name">{{ $prepared_by }}</div>
                <div class="sig-title">Inventory / Asset Officer</div>
                <div style="font-size: 10px; margin-top: 5px;">Date: _________________</div>
            </div>
        </div>

        <div class="signature-box" style="float: right;">
            <p><strong>Approved By:</strong></p>
            <div class="sig-line">
                <div class="sig-name">{{ $approved_by }}</div>
                <div class="sig-title">Project / Office Manager</div>
                <div style="font-size: 10px; margin-top: 5px;">Date: _________________</div>
            </div>
        </div>
        <div style="clear: both;"></div>
    </div>

    <div style="position: absolute; bottom: 0; width: 100%; text-align: center; font-size: 9px; color: #999;">
        Generated by PMIS on {{ now()->format('Y-m-d H:i:s') }}
    </div>
</body>
</html>
